version: '2.4'

services:
  node: &node
    image: node:12-alpine
    container_name: libras_node
    volumes:
      - ./:/node
    working_dir: /node

  api:
    <<: *node
    container_name: libras
    cpu_shares: 512
    mem_limit: 512m
    memswap_limit: 512m
    mem_reservation: 500m
    ports:
      - 3000:3000
    command: npm start

  style:
    <<: *node
    container_name: libras_test_style
    command: npm run test:style

  unit:
    <<: *node
    container_name: libras_test_unit
    command: npm run test:unit

  integration:
    <<: *node
    container_name: libras_test_integration
    command: npm run test:integration

  performance:
    <<: *node
    container_name: libras_test_performance
    depends_on:
      - api
    command: npm run test:performance -- -e docker

  cover:
    <<: *node
    container_name: libras_test_cover
    command: npm run cover
  
  security:
    <<: *node
    container_name: libras_test_security
    command: npm run test:security
